In [1]:
import numpy as np

In [20]:
class ResourceAllocationProblemSolver:
    def __init__(self, A):
        self.A = A
        self.K = A.shape[0]
        self.Q = A.shape[1]
        self.profit_matrix = np.append(A[0].copy().reshape(1, -1), np.zeros((self.K - 1, self.Q)), axis=0)
        self.allocation_matrix = np.append(np.array(list(range(self.Q))).reshape(1, -1), np.zeros((self.K - 1, self.Q)), axis=0)
        
    def calculate_max_profit(self, k, q):
        current_profit = self.A[k][0] + self.profit_matrix[k - 1][0]
        current_resource = 0
        
        for i in range(q + 1):
            other_resources = q - i
            print(f'for current agent {i} other_resources {other_resources}')
            other_profit = self.profit_matrix[k - 1][other_resources]
            print(f"now + other {self.A[k][i]} + {other_profit} current {current_profit}")
            if self.A[k][i] + other_profit > current_profit:
                current_profit = self.A[k][i] + other_profit
                current_resource = i
        return current_profit, current_resource
        
    def solve(self):
        for k in range(1, self.K):
            for q in range(self.Q):
                print(f"agents {k + 1} resources {q}")
                current_profit, current_resource = self.calculate_max_profit(k, q)
                self.profit_matrix[k][q] = current_profit
                self.allocation_matrix[k][q] = current_resource
                print(self.profit_matrix)
                print(self.allocation_matrix)
        q = self.Q - 1
        resolved = np.zeros(self.K)
        for i in range(self.K):
            resolved[self.K - i - 1]  = self.allocation_matrix[self.K - i - 1][int(q)]
            q -=  resolved[self.K - i - 1]
            
        return self.profit_matrix[self.K - 1, self.Q - 1], resolved
        

In [21]:
A = np.array([
    [0, 1, 2, 3],
    [0, 0, 1, 2],
    [0, 2, 2, 3]
])

In [22]:
solver = ResourceAllocationProblemSolver(A)
print(solver.solve())

agents 2 resources 0
for current agent 0 other_resources 0
now + other 0 + 0.0 current 0.0
[[0. 1. 2. 3.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 1. 2. 3.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
agents 2 resources 1
for current agent 0 other_resources 1
now + other 0 + 1.0 current 0.0
for current agent 1 other_resources 0
now + other 0 + 0.0 current 1.0
[[0. 1. 2. 3.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 1. 2. 3.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
agents 2 resources 2
for current agent 0 other_resources 2
now + other 0 + 2.0 current 0.0
for current agent 1 other_resources 1
now + other 0 + 1.0 current 2.0
for current agent 2 other_resources 0
now + other 1 + 0.0 current 2.0
[[0. 1. 2. 3.]
 [0. 1. 2. 0.]
 [0. 0. 0. 0.]]
[[0. 1. 2. 3.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
agents 2 resources 3
for current agent 0 other_resources 3
now + other 0 + 3.0 current 0.0
for current agent 1 other_resources 2
now + other 0 + 2.0 current 3.0
for current agent 2 other_resources 1
now + other 1 + 1.0 current 3.0
for curren